%% ========================================================================
%  SS_Script_v8.m
%  ------------------------------------------------------------------------
%  Combined small-signal state-space driver for the Z-source DC-DC stage
%  of the semi-Z-source inverter (Chapter 3 of revised thesis).
%
%  CHANGE LOG v6 -> v7:
%    V_g updated from 400 V to 500 V to align with Chapter 6 decision
%    (ten PV panels in series at 50 V MPP each = 500 V PV-side DC bus,
%    giving M_nominal = 0.65 against the UK 230 V grid peak of 325.27 V).
%    All operating-point values, plant dynamics, and figures regenerate
%    automatically; the analytical structure of the script is unchanged.
%
%  CHANGE LOG v7 -> v8:
%    L1, L2 changed from 3 mH to 2 mH to match the Simulink simulation
%    model values. C1, C2 changed from 10 uF to 20 uF for the same reason.
%    Both pairs satisfy the inductor ripple and capacitor voltage-ripple
%    design constraints derived in S3.4 (verified numerically). All
%    operating-point values, plant dynamics, resonance frequencies,
%    damping ratios, and figures regenerate automatically.
%
%    Section 14 (L and C sensitivity sweep) sweep ranges were also
%    adjusted to centre on the new nominal values so the tolerance band
%    shading appears in the middle of the figure rather than at one edge.
%
%  This is the single canonical script for Chapter 3 simulation work.
%  It performs:
%    - Three step-response studies (Studies 1, 2, 3)
%    - Operating-point (D0) sensitivity sweep across the MPPT range
%    - Frequency-response analysis (Bode plot) at the nominal operating point
%
%  Each section addresses a specific examiner concern from the viva, and
%  the output figures are formatted for direct thesis inclusion (200 dpi,
%  proper annotations, clear legends).
%
%  ------------------------------------------------------------------------
%  Three step-response studies:
%
%    Study 1 - Small-signal validation (d_hat = 0.01)
%      Validates the linearised state-space model against the Simscape
%      switching model. Both should agree to within switching ripple.
%      Output: Fig_3_5_small_signal.png
%
%    Study 2 - Moderate-signal (d_hat = 0.05)
%      Demonstrates the boundary of the small-signal linearisation. At
%      this excitation the ss() prediction deviates from the true
%      nonlinear behaviour by a measurable amount.
%      Output: Fig_3_6_moderate_signal.png
%
%    Study 3 - Large-signal operating-point step (D: 0.2 -> 0.3)
%      The ss() model linearised about D0 = 0.2 is NOT VALID here and
%      must not be used; only the Simscape switching model can capture
%      this behaviour. The script prints the predicted new steady state
%      as a validation target.
%      Output: Fig_3_7_large_signal.png (generated by topology_Cslx.slx)
%
%  Plant-variation extensions:
%
%    Extension A - D0 sensitivity sweep (Section 12)
%      Rebuilds the small-signal model at 13 operating points from
%      D0 = 0.10 to 0.40. Extracts pole locations, damping ratios, and
%      DC gain at each. Establishes the analytical case for the
%      gain-scheduled PR controller of Chapter 6.
%      Output: Fig_3_10_D0_sweep.png
%
%    Extension B - Frequency response at D0 = 0.20 (Section 13)
%      Bode plot of the control-to-output transfer function Gvd(s).
%      Exposes the twin resonance peaks, partial pole-zero cancellation,
%      and bandwidth constraints for Chapter 6.
%      Output: Fig_3_9_bode.png
%
%  ------------------------------------------------------------------------
%  Naming convention preserved from v2:
%    'D0' in the main script = the operating-point duty ratio about which
%    the small-signal model is linearised. 'D' in local helper functions =
%    a generic duty-ratio argument that accepts D0, D0+d_hat, or D_new.
%
%  Author: Asi-Onob Usang Asi
%  ========================================================================
clear
clc
close all
%% ========================================================================
%% 1. Unified thesis parameter set (Chapters 3, 6, 7)
%% ========================================================================
V_g     = 500;                  % V    PV-side DC voltage (MPP)
                                %      Ten 50 V PV panels in series.
                                %      Updated from 400 V (v6) to align
                                %      with Chapter 6 modulation budget
                                %      (M_nominal = 325.27/500 = 0.65).
P_rated = 3000;                 % W    rated DC-DC output
D0      = 0.2;                  % -    operating-point duty ratio
Kd0     = 1 - D0;               % -    complement of D0
L1   = 2e-3;   L2   = 2e-3;     % H    Z-network inductance (v8: was 3 mH)
C1   = 20e-6;  C2   = 20e-6;    % F    Z-network capacitance (v8: was 10 uF)
r_L   = 50e-3;                  % Ohm  inductor DCR
R_on  = 100e-3;                 % Ohm  MOSFET on-resistance
V_F   = 1.0;                    % V    diode forward drop
r_C   = 20e-3;                  % Ohm  capacitor ESR (typical film cap)
r_L_eff = r_L + D0*R_on;        % Ohm  averaged inductor branch R at D0
% Capacitor ESR (r_C) is now included in the averaged model. At the dominant
% natural frequencies, the capacitor impedance |Z_C| ~ 20 Ohm is still three
% orders of magnitude larger than r_C ~ 20 mOhm, so the qualitative dynamics
% are unchanged. Pole locations shift by < 0.03 % and damping ratios shift
% by < 0.001 (analytical estimate verified numerically in this script).
% The inclusion serves methodological completeness rather than altering
% quantitative conclusions.
%% ========================================================================
%% 2. Steady-state operating point at D0 = 0.2
%% ========================================================================
[Vo, V_c1, V_c2, I_L1, I_L2, R] = operating_point(V_g, D0, P_rated);
fprintf('\n===== Operating point at D0 = %.3f =====\n', D0);
fprintf('   V_g     = %7.2f V\n',  V_g);
fprintf('   V_C1    = %7.2f V\n',  V_c1);
fprintf('   V_C2    = %7.2f V   (DC-bus output)\n',  V_c2);
fprintf('   I_L1    = %7.3f A\n',  I_L1);
fprintf('   I_L2    = %7.3f A\n',  I_L2);
fprintf('   R       = %7.2f Ohm (load for %d W)\n', R, P_rated);
fprintf('   r_L_eff = %.3f Ohm\n', r_L_eff);
%% ========================================================================
%% 3. Build the small-signal state-space model about D0 = 0.2
%% ========================================================================
% State x = [i_L1; i_L2; v_C1; v_C2];  input u = d_hat; output y = v_terminal,C2
%
% The model now includes capacitor ESR (r_C). With ESR, the voltage at the
% capacitor's external terminal is v_term = v_C + i_C*r_C, where v_C is the
% (ideal) capacitor state and i_C is the current flowing into the capacitor.
% This modification propagates two ways:
%   1. The inductor equations see the terminal voltages (vC1 + iC1*r_C) and
%      (vC2 + iC2*r_C) rather than vC1 and vC2 directly.
%   2. The output y is the voltage AT THE LOAD = v_terminal,C2, so the C
%      matrix is no longer [0 0 0 1] but has terms that depend on i_L1, i_L2.
%
% K_d_ind and K_d_cap arise from evaluating (A1 - A2)*X + (B1 - B2)*U at
% the operating point. The B vector is essentially unchanged by ESR (the
% ESR corrections to B are second-order in r_C/R ~ 7e-4).
% ------------------------------------------------------------------------
K_d_ind = V_c2 - V_c1 - V_g;
K_d_cap = I_L1 + I_L2;
% A matrix with capacitor ESR (full derivation in SS_ESR_Derivation.docx).
% Reduces to the original A when r_C = 0 (verified by cross-check).
%
% A[0,1] and A[1,0] are NEW entries (cross-coupling between iL1 and iL2)
% that appear only when r_C > 0. The on-diagonal inductor terms gain
% additional ESR-loss contributions. The load pole at A[3,3] shifts from
% -1/(R*C2) to -1/((R+r_C)*C2).
A = [ ( -R*r_C*(D0-1)^2 - (R+r_C)*(D0^2*r_C + r_L_eff) ) / (L1*(R+r_C)), ...
        -D0*r_C*(D0-1)*(2*R + r_C) / (L1*(R+r_C)), ...
        D0/L1, ...
        R*(D0-1) / (L1*(R+r_C)); ...
      -D0*r_C*(D0-1)*(2*R + r_C) / (L2*(R+r_C)), ...
       ( -D0^2*R*r_C - (R+r_C)*(r_C*(D0-1)^2 + r_L_eff) ) / (L2*(R+r_C)), ...
       (D0-1)/L2, ...
       D0*R / (L2*(R+r_C)); ...
      -D0/C1,  (1-D0)/C1,  0,  0; ...
       R*(1-D0)/(C2*(R+r_C)), ...
       -D0*R/(C2*(R+r_C)), ...
       0, ...
       -1/(C2*(R+r_C)) ];
B = [  K_d_ind/L1;  K_d_ind/L2;  -K_d_cap/C1;  -K_d_cap/C2 ];
% Output matrix C: y = v_terminal,C2 = vC2 + iC2*r_C, with the averaged
% iC2 expressed in terms of states. Reduces to [0 0 0 1] when r_C = 0.
Cm = [ R*r_C*(1-D0)/(R+r_C), ...
      -R*r_C*D0/(R+r_C), ...
       0, ...
       R/(R+r_C) ];
Dm = 0;
sys_ss = ss(A, B, Cm, Dm);
sys_ss.StateName  = {'i_L1','i_L2','v_C1','v_C2'};
sys_ss.InputName  = 'd_hat';
sys_ss.OutputName = 'v_C2_hat';
G_vd = tf(sys_ss);
%% ========================================================================
%% 4. Pole-zero analysis
%% ========================================================================
P_vec = pole(sys_ss);
fprintf('\n===== Pole-zero analysis =====\n');
for k = 1:length(P_vec)
    s = P_vec(k);
    if abs(imag(s)) < 1e-6
        fprintf('   s_%d = %+10.4e          (real)\n', k, real(s));
    else
        wn = abs(s); zeta = -real(s)/wn;
        fprintf('   s_%d = %+10.4e %+8.4ej   wn = %.1f rad/s (%.1f Hz), zeta = %.4f\n', ...
                k, real(s), imag(s), wn, wn/(2*pi), zeta);
    end
end
% --- Figure 3.8: pole-zero map ----------------------------------------
% Visualisation of the four poles and three zeros of Gvd(s) on the s-plane.
% Use MATLAB's built-in pzmap which handles axis scaling automatically.
figure('Color','w','Position',[140 140 800 700]);
pzmap(sys_ss);
grid on; box on;
title('Figure 3.8 - Pole-zero map of G_{vd}(s) at D_0 = 0.20', ...
      'FontSize', 13, 'FontWeight','bold');
xlabel('Real axis (rad/s)', 'FontSize', 11);
ylabel('Imaginary axis (rad/s)', 'FontSize', 11);
set(gca, 'FontSize', 10);
% Annotate the modes (find pole pairs and label them)
P_complex = P_vec(abs(imag(P_vec)) > 1e-6);
P_upper   = P_complex(imag(P_complex) > 0);   % upper-half-plane representatives
[~, sort_idx] = sort(abs(P_upper));
P_upper = P_upper(sort_idx);
if length(P_upper) >= 1
    p1 = P_upper(1);
    text(real(p1), imag(p1) + 400, ...
         sprintf(' Mode 1: %.0f Hz, \\zeta = %.3f', abs(p1)/(2*pi), -real(p1)/abs(p1)), ...
         'FontSize', 9, 'Color', [0.10 0.37 0.65], 'FontWeight','bold', ...
         'BackgroundColor','w', 'EdgeColor', [0.7 0.7 0.7], 'Margin', 3);
end
if length(P_upper) >= 2
    p2 = P_upper(2);
    text(real(p2), imag(p2) + 400, ...
         sprintf(' Mode 2: %.0f Hz, \\zeta = %.3f', abs(p2)/(2*pi), -real(p2)/abs(p2)), ...
         'FontSize', 9, 'Color', [0.75 0.25 0.10], 'FontWeight','bold', ...
         'BackgroundColor','w', 'EdgeColor', [0.7 0.7 0.7], 'Margin', 3);
end
drawnow;
print(gcf, 'Fig_3_8_pole_zero_map.png', '-dpng', '-r200');
fprintf('\n   Figure saved: Fig_3_8_pole_zero_map.png (200 dpi)\n');
%% ========================================================================
%% 5. SIMULATION SETTINGS
%% ========================================================================
dt     = 1e-5;                  % 10 us fixed step
t_sim  = 0.20;                  % 200 ms total
t_step = 0.05;                  % step at 50 ms
t      = (0:dt:t_sim)';
% Style constants used throughout the plots
COL_RED   = [0.85 0.10 0.10];   % primary trace
COL_GREEN = [0.0 0.5 0.2];      % nonlinear target / good
COL_BLUE  = [0.10 0.37 0.65];   % Mode 1
COL_M2    = [0.75 0.25 0.10];   % Mode 2
COL_GREY  = [0.3 0.3 0.3];      % operating point
COL_FAINT = [0.5 0.5 0.5];      % step time
COL_K     = [0.20 0.20 0.20];   % monotonic curves
COL_REGIME = [0.95 0.92 0.78];  % regime-change band
COL_SHADE = [0.95 0.95 0.98];   % pre-step band
COL_GAP   = [1.0 0.95 0.7];     % linearisation gap
%% ========================================================================
%% 6. STUDY 1: Small-signal validation (d_hat = 0.01)
%% ========================================================================
fprintf('\n===== STUDY 1: Small-signal (d_hat = 0.01) =====\n');
d_hat_1 = 0.01;
[y1, info_1, V_true_1] = run_step_study(sys_ss, V_c2, V_g, D0, d_hat_1, ...
                                         t, t_step, P_rated);
err_pct_1 = 100*(V_c2 + y1(end) - V_true_1)/V_true_1;
figure('Color','w','Position',[80 80 1100 700]);
subplot(2,1,1); hold on; grid on; box on;
y_lo = min(V_c2 + y1) - 1;  y_hi = max(V_c2 + y1) + 1;
patch([0 t_step*1e3 t_step*1e3 0], [y_lo y_lo y_hi y_hi], ...
      COL_SHADE, 'EdgeColor','none', 'FaceAlpha', 0.4, ...
      'HandleVisibility', 'off');
h_ss = plot(t*1e3, V_c2 + y1, 'Color', COL_RED, 'LineWidth', 2, ...
            'DisplayName', sprintf('ss() response (\\Deltad = %.3f)', d_hat_1));
h_op = yline(V_c2, '-', 'Color', COL_GREY, 'LineWidth', 1.2, ...
             'DisplayName', sprintf('Operating point V_{C2,0} = %.2f V', V_c2));
h_ss_final = yline(V_c2 + y1(end), '--', 'Color', COL_RED, 'LineWidth', 1.5, ...
                   'DisplayName', sprintf('ss() final = %.2f V', V_c2 + y1(end)));
h_true = yline(V_true_1, ':', 'Color', COL_GREEN, 'LineWidth', 2, ...
               'DisplayName', sprintf('Nonlinear target = %.2f V', V_true_1));
xline(t_step*1e3, ':', 'Color', COL_FAINT, 'LineWidth', 1, ...
      'Label', sprintf('Step at t = %.0f ms', t_step*1e3), ...
      'LabelOrientation','horizontal', 'LabelVerticalAlignment','top', ...
      'FontSize', 9, 'HandleVisibility', 'off');
xlabel('Time (ms)', 'FontSize', 11);
ylabel('v_{C2} (V)', 'FontSize', 11);
title(sprintf('(a) Study 1 - Small-signal validation: \\Deltad = %.3f at t = %.0f ms', ...
              d_hat_1, t_step*1e3), 'FontSize', 12, 'FontWeight','bold');
legend([h_ss h_op h_ss_final h_true], 'Location', 'best', 'FontSize', 9, ...
       'Box', 'on', 'EdgeColor', [0.7 0.7 0.7]);
set(gca, 'FontSize', 10);
text(0.98, 0.05, sprintf('Linearisation error: %+.2f %%', err_pct_1), ...
     'Units','normalized', 'HorizontalAlignment','right', ...
     'VerticalAlignment','bottom', 'FontSize', 10, ...
     'FontWeight','bold', 'Color', COL_GREEN, ...
     'BackgroundColor', 'w', 'EdgeColor', [0.7 0.7 0.7], 'Margin', 5);
subplot(2,1,2); hold on; grid on; box on;
zm = (t >= t_step - 2e-3) & (t <= t_step + 30e-3);
plot((t(zm)-t_step)*1e3, y1(zm), 'Color', COL_RED, 'LineWidth', 2);
yline(0, '-', 'Color', COL_GREY, 'LineWidth', 1);
yline(y1(end), '--', 'Color', COL_RED, 'LineWidth', 1.5);
xline(0, ':', 'Color', COL_FAINT, 'LineWidth', 1, ...
      'Label', 'Step time', 'LabelOrientation','horizontal', ...
      'LabelHorizontalAlignment','center', 'FontSize', 9);
sb = 0.02 * abs(y1(end));
yline(y1(end)+sb, ':', 'Color', COL_FAINT, 'LineWidth', 0.8);
yline(y1(end)-sb, ':', 'Color', COL_FAINT, 'LineWidth', 0.8);
xlabel('Time after step (ms)', 'FontSize', 11);
ylabel('\Deltav_{C2} (V)', 'FontSize', 11);
title(sprintf('(b) Transient detail - t_{s,2%%} = %.2f ms, overshoot = %.1f %%', ...
              1e3*info_1.SettlingTime, info_1.Overshoot), ...
      'FontSize', 12, 'FontWeight','bold');
set(gca, 'FontSize', 10);
if info_1.SettlingTime > 0 && info_1.SettlingTime < 0.030
    xline(1e3*info_1.SettlingTime, '-.', 'Color', COL_GREEN, 'LineWidth', 1.2, ...
          'Label', sprintf('t_s = %.2f ms', 1e3*info_1.SettlingTime), ...
          'LabelHorizontalAlignment','right', 'LabelVerticalAlignment','middle', ...
          'FontSize', 9, 'Color', [0.0 0.4 0.15]);
end
drawnow;
print(gcf, 'Fig_3_5_small_signal.png', '-dpng', '-r200');
fprintf('   Figure saved: Fig_3_5_small_signal.png (200 dpi)\n');
%% ========================================================================
%% 7. STUDY 2: Moderate-signal boundary (d_hat = 0.05)
%% ========================================================================
fprintf('\n===== STUDY 2: Moderate-signal (d_hat = 0.05) =====\n');
d_hat_2 = 0.05;
[y2, info_2, V_true_2] = run_step_study(sys_ss, V_c2, V_g, D0, d_hat_2, ...
                                         t, t_step, P_rated);
err_pct = 100*(V_c2 + y2(end) - V_true_2)/V_true_2;
fprintf('   Linearisation error vs nonlinear target = %.2f%%\n', err_pct);
figure('Color','w','Position',[120 120 1100 700]);
subplot(2,1,1); hold on; grid on; box on;
y_lo = min(V_c2 + y2) - 1;  y_hi = max(V_c2 + y2) + 1;
patch([0 t_step*1e3 t_step*1e3 0], [y_lo y_lo y_hi y_hi], ...
      COL_SHADE, 'EdgeColor','none', 'FaceAlpha', 0.4, ...
      'HandleVisibility', 'off');
h_ss = plot(t*1e3, V_c2 + y2, 'Color', COL_RED, 'LineWidth', 2, ...
            'DisplayName', sprintf('ss() response (\\Deltad = %.3f)', d_hat_2));
h_op = yline(V_c2, '-', 'Color', COL_GREY, 'LineWidth', 1.2, ...
             'DisplayName', sprintf('Operating point V_{C2,0} = %.2f V', V_c2));
h_ss_final = yline(V_c2 + y2(end), '--', 'Color', COL_RED, 'LineWidth', 1.5, ...
                   'DisplayName', sprintf('ss() final = %.2f V', V_c2 + y2(end)));
h_true = yline(V_true_2, ':', 'Color', COL_GREEN, 'LineWidth', 2, ...
               'DisplayName', sprintf('Nonlinear target = %.2f V', V_true_2));
% Shade the linearisation gap (visually proves ss() vs nonlinear disagree)
y_gap_min = min(V_c2 + y2(end), V_true_2);
y_gap_max = max(V_c2 + y2(end), V_true_2);
patch([t_step*1e3 t_sim*1e3 t_sim*1e3 t_step*1e3], ...
      [y_gap_min y_gap_min y_gap_max y_gap_max], ...
      COL_GAP, 'EdgeColor','none', 'FaceAlpha', 0.5, ...
      'HandleVisibility', 'off');
xline(t_step*1e3, ':', 'Color', COL_FAINT, 'LineWidth', 1, ...
      'Label', sprintf('Step at t = %.0f ms', t_step*1e3), ...
      'LabelOrientation','horizontal', 'LabelVerticalAlignment','top', ...
      'FontSize', 9, 'HandleVisibility', 'off');
xlabel('Time (ms)', 'FontSize', 11);
ylabel('v_{C2} (V)', 'FontSize', 11);
title(sprintf('(a) Study 2 - Moderate-signal: \\Deltad = %.3f at t = %.0f ms', ...
              d_hat_2, t_step*1e3), 'FontSize', 12, 'FontWeight','bold');
legend([h_ss h_op h_ss_final h_true], 'Location', 'best', 'FontSize', 9, ...
       'Box', 'on', 'EdgeColor', [0.7 0.7 0.7]);
set(gca, 'FontSize', 10);
text(0.98, 0.05, sprintf('Linearisation error: %+.2f %%\n(shaded yellow band)', err_pct), ...
     'Units','normalized', 'HorizontalAlignment','right', ...
     'VerticalAlignment','bottom', 'FontSize', 10, ...
     'FontWeight','bold', 'Color', [0.6 0.4 0.0], ...
     'BackgroundColor', 'w', 'EdgeColor', [0.7 0.7 0.7], 'Margin', 5);
subplot(2,1,2); hold on; grid on; box on;
zm = (t >= t_step - 2e-3) & (t <= t_step + 30e-3);
plot((t(zm)-t_step)*1e3, y2(zm), 'Color', COL_RED, 'LineWidth', 2);
yline(0, '-', 'Color', COL_GREY, 'LineWidth', 1);
yline(y2(end), '--', 'Color', COL_RED, 'LineWidth', 1.5);
xline(0, ':', 'Color', COL_FAINT, 'LineWidth', 1, ...
      'Label', 'Step time', 'LabelOrientation','horizontal', ...
      'LabelHorizontalAlignment','center', 'FontSize', 9);
sb = 0.02 * abs(y2(end));
yline(y2(end)+sb, ':', 'Color', COL_FAINT, 'LineWidth', 0.8);
yline(y2(end)-sb, ':', 'Color', COL_FAINT, 'LineWidth', 0.8);
xlabel('Time after step (ms)', 'FontSize', 11);
ylabel('\Deltav_{C2} (V)', 'FontSize', 11);
title(sprintf('(b) Transient detail - t_{s,2%%} = %.2f ms, overshoot = %.1f %%', ...
              1e3*info_2.SettlingTime, info_2.Overshoot), ...
      'FontSize', 12, 'FontWeight','bold');
set(gca, 'FontSize', 10);
if info_2.SettlingTime > 0 && info_2.SettlingTime < 0.030
    xline(1e3*info_2.SettlingTime, '-.', 'Color', COL_GREEN, 'LineWidth', 1.2, ...
          'Label', sprintf('t_s = %.2f ms', 1e3*info_2.SettlingTime), ...
          'LabelHorizontalAlignment','right', 'LabelVerticalAlignment','middle', ...
          'FontSize', 9, 'Color', [0.0 0.4 0.15]);
end
drawnow;
print(gcf, 'Fig_3_6_moderate_signal.png', '-dpng', '-r200');
fprintf('   Figure saved: Fig_3_6_moderate_signal.png (200 dpi)\n');
%% ========================================================================
%% 8. STUDY 3: Large-signal operating-point step (D0 -> 0.3)
%% ========================================================================
fprintf('\n===== STUDY 3: Large-signal operating-point step =====\n');
D_new = 0.3;
[Vo_new, Vc1_new, Vc2_new, IL1_new, IL2_new, R_new] = ...
    operating_point(V_g, D_new, P_rated);
fprintf('   Linearisation point (D0 = %.2f):\n', D0);
fprintf('      V_C2 = %.2f V,  I_L1 = %.3f A,  R = %.2f Ohm\n', ...
        V_c2, I_L1, R);
fprintf('   New steady state target (D = %.2f):\n', D_new);
fprintf('      V_C2 = %.2f V,  I_L1 = %.3f A,  R = %.2f Ohm\n', ...
        Vc2_new, IL1_new, R_new);
fprintf('   Voltage change: %.2f V (%.1f %%)\n', ...
        Vc2_new - V_c2, 100*(Vc2_new - V_c2)/V_c2);
fprintf('\n   The ss() model linearised about D0 = %.2f is NOT VALID for\n', D0);
fprintf('   this step. To generate Figure 3.7, run topology_Cslx.slx with:\n');
fprintf('      V_g       = 500 V\n');
fprintf('      R         = %.2f Ohm  (hold R fixed to test duty-ratio\n', R);
fprintf('                              response alone; see note below)\n');
fprintf('      Step time = 0.05 s\n');
fprintf('      Step from D = 0.2 to D = 0.3\n');
fprintf('      Stop time = 0.20 s\n');
fprintf('\n   NOTE on load resistance:\n');
fprintf('   Holding R = %.2f Ohm (matched to 3 kW at D0 = 0.2) isolates\n', R);
fprintf('   the duty-ratio dynamics. At D = 0.3 with this R, the output\n');
fprintf('   will settle at V_C2 = %.2f V delivering P = %.1f W. Do NOT\n', ...
        Vc2_new, Vc2_new^2/R);
fprintf('   adjust R for this step - the Chapter 6 closed-loop controller\n');
fprintf('   handles power regulation separately.\n');
%% ========================================================================
%% 9. Summary table (for Chapter 3 Table 3.2)
%% ========================================================================
fprintf('\n\n===== SUMMARY: comparison of three step-response studies =====\n');
fprintf('  Study   | d_hat | ss() final | nonlinear  | error    | ts(2%%)\n');
fprintf('  --------+-------+------------+------------+----------+--------\n');
fprintf('  1 (sml) | %.3f | %9.3f V | %9.3f V | %+6.2f %% | %5.2f ms\n', ...
        d_hat_1, V_c2 + y1(end), V_true_1, ...
        100*(V_c2 + y1(end) - V_true_1)/V_true_1, ...
        1e3*info_1.SettlingTime);
fprintf('  2 (mod) | %.3f | %9.3f V | %9.3f V | %+6.2f %% | %5.2f ms\n', ...
        d_hat_2, V_c2 + y2(end), V_true_2, ...
        100*(V_c2 + y2(end) - V_true_2)/V_true_2, ...
        1e3*info_2.SettlingTime);
fprintf('  3 (lrg) | 0.100 |     ss() INVALID     | %9.3f V |    -    |    -  \n', ...
        Vc2_new);
%% ========================================================================
%% 10. Save all results
%% ========================================================================
ss_result.t                      = t;
ss_result.small.d_hat            = d_hat_1;
ss_result.small.v_C2             = V_c2 + y1;
ss_result.small.nonlinear_target = V_true_1;
ss_result.small.metrics          = info_1;
ss_result.moderate.d_hat         = d_hat_2;
ss_result.moderate.v_C2          = V_c2 + y2;
ss_result.moderate.nonlinear_target = V_true_2;
ss_result.moderate.metrics       = info_2;
ss_result.large.D0_lin           = D0;
ss_result.large.D_new            = D_new;
ss_result.large.V_C2_new         = Vc2_new;
ss_result.large.note             = 'ss() not valid; run topology_Cslx.slx at D=0.3';
ss_result.params.V_g             = V_g;
ss_result.params.D0              = D0;
ss_result.params.L1              = L1;
ss_result.params.C1              = C1;
ss_result.params.R               = R;
ss_result.params.r_L_eff         = r_L_eff;
save('ss_model_result.mat', 'ss_result');
fprintf('\nResults saved to ss_model_result.mat\n');
%% ========================================================================
%% 11. Optional: auto-tune PI gains using Control System Toolbox
%% ========================================================================
% This section is COMMENTED OUT by default. Chapter 3 is about open-loop
% plant characterisation, not closed-loop controller design. Uncomment
% only from the Chapter 6 driver script:
%
%   [Cpi, pidinfo] = pidtune(G_vd, 'PI', 'DesignFocus','reference-tracking');
%   fprintf('Auto-tuned PI: Kp = %.4f, Ki = %.4f\n', Cpi.Kp, Cpi.Ki);
fprintf('\n--- Studies 1-3 complete ---\n');
%% ========================================================================
%% 12. EXTENSION A: Operating-point (D0) sensitivity sweep
%% ========================================================================
% Sweeps the linearisation point D0 across the realistic MPPT operating
% range and rebuilds the small-signal model at each point. Extracts the
% dominant-mode natural frequency, damping ratio, and DC gain at each D0.
%
% Purpose: provides the analytical justification for the gain-scheduled
% PR controller adopted in Chapter 6. A fixed-gain controller designed
% at a single D0 would not maintain consistent closed-loop performance
% across the MPPT operating range - this section quantifies the variation.
% ========================================================================
fprintf('\n===== EXTENSION A: D0 sensitivity sweep =====\n');
D0_sweep = 0.10 : 0.025 : 0.40;
N_sweep  = length(D0_sweep);
fn_mode1   = zeros(N_sweep, 1);
zeta_mode1 = zeros(N_sweep, 1);
fn_mode2   = zeros(N_sweep, 1);
zeta_mode2 = zeros(N_sweep, 1);
n_complex  = zeros(N_sweep, 1);
dcgain_vec = zeros(N_sweep, 1);
VC2_ss     = zeros(N_sweep, 1);
ts_2pct    = zeros(N_sweep, 1);
for k = 1:N_sweep
    D0_k  = D0_sweep(k);
    Kd0_k = 1 - D0_k;
    [~, V_c1_k, V_c2_k, I_L1_k, I_L2_k, R_k] = operating_point(V_g, D0_k, P_rated);
    r_L_eff_k = r_L + D0_k * R_on;
    K_d_ind_k = V_c2_k - V_c1_k - V_g;
    K_d_cap_k = I_L1_k + I_L2_k;
    % A matrix with capacitor ESR (same form as Section 3)
    A_k = [ ( -R_k*r_C*(D0_k-1)^2 - (R_k+r_C)*(D0_k^2*r_C + r_L_eff_k) ) / (L1*(R_k+r_C)), ...
              -D0_k*r_C*(D0_k-1)*(2*R_k + r_C) / (L1*(R_k+r_C)), ...
              D0_k/L1, ...
              R_k*(D0_k-1) / (L1*(R_k+r_C)); ...
            -D0_k*r_C*(D0_k-1)*(2*R_k + r_C) / (L2*(R_k+r_C)), ...
             ( -D0_k^2*R_k*r_C - (R_k+r_C)*(r_C*(D0_k-1)^2 + r_L_eff_k) ) / (L2*(R_k+r_C)), ...
             (D0_k-1)/L2, ...
             D0_k*R_k / (L2*(R_k+r_C)); ...
            -D0_k/C1,  (1-D0_k)/C1,  0,  0; ...
             R_k*(1-D0_k)/(C2*(R_k+r_C)), ...
             -D0_k*R_k/(C2*(R_k+r_C)), ...
             0, ...
             -1/(C2*(R_k+r_C)) ];
    B_k = [ K_d_ind_k/L1; K_d_ind_k/L2; -K_d_cap_k/C1; -K_d_cap_k/C2 ];
    % Output matrix C with ESR
    Cm_k = [ R_k*r_C*(1-D0_k)/(R_k+r_C), ...
            -R_k*r_C*D0_k/(R_k+r_C), ...
             0, ...
             R_k/(R_k+r_C) ];
    sys_k = ss(A_k, B_k, Cm_k, Dm);
    P_k = pole(sys_k);
    cplx_idx = abs(imag(P_k)) > 1e-6;
    P_cplx   = P_k(cplx_idx);
    n_complex(k) = length(P_cplx) / 2;
    if length(P_cplx) >= 2
        wn_cplx = unique(abs(P_cplx));
        wn_cplx = sort(wn_cplx);
        fn_mode1(k) = wn_cplx(1) / (2*pi);
        idx1 = find(abs(abs(P_cplx) - wn_cplx(1)) < 1e-3, 1);
        zeta_mode1(k) = -real(P_cplx(idx1)) / abs(P_cplx(idx1));
        if length(wn_cplx) >= 2
            fn_mode2(k) = wn_cplx(2) / (2*pi);
            idx2 = find(abs(abs(P_cplx) - wn_cplx(2)) < 1e-3, 1);
            zeta_mode2(k) = -real(P_cplx(idx2)) / abs(P_cplx(idx2));
        else
            fn_mode2(k) = NaN; zeta_mode2(k) = NaN;
        end
    else
        fn_mode1(k) = NaN; zeta_mode1(k) = NaN;
        fn_mode2(k) = NaN; zeta_mode2(k) = NaN;
    end
    dcgain_vec(k) = dcgain(sys_k);
    VC2_ss(k)     = V_c2_k;
    t_test = 0:1e-5:0.05;
    [y_test, ~] = step(sys_k, t_test);
    info_test = stepinfo(y_test, t_test, y_test(end), 'SettlingTimeThreshold', 0.02);
    ts_2pct(k) = info_test.SettlingTime;
end
% Print summary at representative operating points
idx_show = [find(abs(D0_sweep - 0.15) < 1e-6), ...
            find(abs(D0_sweep - 0.20) < 1e-6), ...
            find(abs(D0_sweep - 0.30) < 1e-6)];
fprintf('\n  D0    | V_C2(V)| Mode 1: fn(Hz)  zeta  | Mode 2: fn(Hz)  zeta  | DC gain  | ts_2%%(ms)\n');
fprintf('  ------+--------+------------------------+-----------------------+----------+----------\n');
for k = idx_show
    if isnan(fn_mode2(k))
        fprintf('  %.3f | %6.1f | %12.1f  %6.3f | %12s  %6s | %+8.2f | %7.2f\n', ...
                D0_sweep(k), VC2_ss(k), fn_mode1(k), zeta_mode1(k), ...
                '(real pole)', '   --', dcgain_vec(k), ts_2pct(k)*1e3);
    else
        fprintf('  %.3f | %6.1f | %12.1f  %6.3f | %12.1f  %6.3f | %+8.2f | %7.2f\n', ...
                D0_sweep(k), VC2_ss(k), fn_mode1(k), zeta_mode1(k), ...
                fn_mode2(k), zeta_mode2(k), dcgain_vec(k), ts_2pct(k)*1e3);
    end
end
regime_change_idx = find(n_complex < 2, 1, 'first');
if ~isempty(regime_change_idx)
    D0_regime = D0_sweep(regime_change_idx);
    fprintf('\n  Regime change: at D0 >= %.3f, the higher-frequency mode splits\n', D0_regime);
    fprintf('  into two real poles. Below this threshold both modes are complex pairs.\n');
else
    D0_regime = 0.40;  % fallback if no regime change found in this range
end
% --- Polished plot --------------------------------------------------
figure('Color','w','Position',[80 80 1100 750]);
% Panel (a): Natural frequencies
subplot(2,2,1); hold on; grid on; box on;
patch([D0_regime D0_sweep(end) D0_sweep(end) D0_regime], ...
      [400 400 1000 1000], COL_REGIME, 'EdgeColor','none', ...
      'FaceAlpha', 0.5, 'HandleVisibility','off');
plot(D0_sweep, fn_mode1, '-o', 'Color', COL_BLUE, 'MarkerFaceColor', COL_BLUE, ...
     'LineWidth', 1.8, 'MarkerSize', 5, 'DisplayName', 'Mode 1 (dominant)');
plot(D0_sweep, fn_mode2, '-s', 'Color', COL_M2, 'MarkerFaceColor', COL_M2, ...
     'LineWidth', 1.8, 'MarkerSize', 5, 'DisplayName', 'Mode 2');
xline(0.20, '--', 'Color', [0.4 0.4 0.4], 'LineWidth', 1.2, ...
      'Label', 'D_0 nominal', 'LabelOrientation','horizontal', ...
      'LabelHorizontalAlignment','center', 'LabelVerticalAlignment','top', ...
      'FontSize', 9, 'HandleVisibility', 'off');
text((D0_regime + D0_sweep(end))/2, 980, 'Mode 2 = real poles', ...
     'FontSize', 9, 'HorizontalAlignment','center', ...
     'Color', [0.5 0.35 0.05], 'FontAngle','italic');
xlabel('Operating point D_0', 'FontSize', 11);
ylabel('Natural frequency f_n (Hz)', 'FontSize', 11);
title('(a) Mode natural frequencies', 'FontSize', 12, 'FontWeight','bold');
xlim([D0_sweep(1)-0.01 D0_sweep(end)+0.01]);
ylim([400 1000]);
legend('Location','southwest','FontSize', 9, 'Box','off');
set(gca, 'FontSize', 10);
% Panel (b): Damping ratios (headline finding)
subplot(2,2,2); hold on; grid on; box on;
patch([D0_regime D0_sweep(end) D0_sweep(end) D0_regime], ...
      [0 0 0.85 0.85], COL_REGIME, 'EdgeColor','none', ...
      'FaceAlpha', 0.5, 'HandleVisibility','off');
plot(D0_sweep, zeta_mode1, '-o', 'Color', COL_BLUE, 'MarkerFaceColor', COL_BLUE, ...
     'LineWidth', 1.8, 'MarkerSize', 5, 'DisplayName', 'Mode 1');
plot(D0_sweep, zeta_mode2, '-s', 'Color', COL_M2, 'MarkerFaceColor', COL_M2, ...
     'LineWidth', 1.8, 'MarkerSize', 5, 'DisplayName', 'Mode 2');
yline(0.7, ':', 'Color', COL_GREEN, 'LineWidth', 1.2, ...
      'Label', '\zeta = 0.7 (typical design target)', ...
      'LabelHorizontalAlignment','left', 'FontSize', 9, ...
      'HandleVisibility', 'off');
xline(0.20, '--', 'Color', [0.4 0.4 0.4], 'LineWidth', 1.2, ...
      'Label', 'D_0 nominal', 'LabelOrientation','horizontal', ...
      'LabelHorizontalAlignment','center', 'LabelVerticalAlignment','bottom', ...
      'FontSize', 9, 'HandleVisibility', 'off');
% Annotate the damping-ratio peak in the complex regime
if ~isempty(regime_change_idx) && regime_change_idx > 1
    [zmax, i_zmax] = max(zeta_mode1(1:regime_change_idx-1));
else
    [zmax, i_zmax] = max(zeta_mode1);
end
plot(D0_sweep(i_zmax), zmax, 'o', 'MarkerSize', 11, 'LineWidth', 2, ...
     'Color', COL_BLUE, 'HandleVisibility','off');
text(D0_sweep(i_zmax)+0.005, zmax-0.05, ...
     sprintf('peak \\zeta = %.2f at D_0 = %.3f', zmax, D0_sweep(i_zmax)), ...
     'FontSize', 9, 'Color', COL_BLUE, 'FontWeight','bold');
xlabel('Operating point D_0', 'FontSize', 11);
ylabel('Damping ratio \zeta', 'FontSize', 11);
title('(b) Mode damping ratios', 'FontSize', 12, 'FontWeight','bold');
xlim([D0_sweep(1)-0.01 D0_sweep(end)+0.01]);
ylim([0 0.85]);
legend('Location','northwest','FontSize', 9, 'Box','off');
set(gca, 'FontSize', 10);
% Panel (c): Settling time
subplot(2,2,3); hold on; grid on; box on;
ymax_ts = max(ts_2pct*1e3)*1.15;
patch([D0_regime D0_sweep(end) D0_sweep(end) D0_regime], ...
      [0 0 ymax_ts ymax_ts], COL_REGIME, 'EdgeColor','none', 'FaceAlpha', 0.5);
plot(D0_sweep, ts_2pct*1e3, '-o', 'Color', COL_K, 'MarkerFaceColor', COL_K, ...
     'LineWidth', 1.8, 'MarkerSize', 5);
xline(0.20, '--', 'Color', [0.4 0.4 0.4], 'LineWidth', 1.2, ...
      'Label', 'D_0 nominal', 'LabelOrientation','horizontal', ...
      'LabelHorizontalAlignment','center', 'LabelVerticalAlignment','top', ...
      'FontSize', 9);
[tmin, i_tmin] = min(ts_2pct);
plot(D0_sweep(i_tmin), tmin*1e3, 'o', 'MarkerSize', 11, 'LineWidth', 2, ...
     'Color', COL_GREEN);
text(D0_sweep(i_tmin)-0.02, tmin*1e3 + 1.5, ...
     sprintf('min t_s = %.1f ms\n at D_0 = %.3f', tmin*1e3, D0_sweep(i_tmin)), ...
     'FontSize', 9, 'Color', [0.0 0.4 0.15], 'FontWeight','bold');
xlabel('Operating point D_0', 'FontSize', 11);
ylabel('2% settling time t_s (ms)', 'FontSize', 11);
title('(c) Step-response settling time', 'FontSize', 12, 'FontWeight','bold');
xlim([D0_sweep(1)-0.01 D0_sweep(end)+0.01]);
ylim([0 ymax_ts]);
set(gca, 'FontSize', 10);
% Panel (d): DC gain
subplot(2,2,4); hold on; grid on; box on;
ymin_dc = min(dcgain_vec)*1.1;
patch([D0_regime D0_sweep(end) D0_sweep(end) D0_regime], ...
      [ymin_dc ymin_dc 0 0], COL_REGIME, 'EdgeColor','none', 'FaceAlpha', 0.5);
plot(D0_sweep, dcgain_vec, '-o', 'Color', COL_K, 'MarkerFaceColor', COL_K, ...
     'LineWidth', 1.8, 'MarkerSize', 5);
xline(0.20, '--', 'Color', [0.4 0.4 0.4], 'LineWidth', 1.2, ...
      'Label', 'D_0 nominal', 'LabelOrientation','horizontal', ...
      'LabelHorizontalAlignment','center', 'LabelVerticalAlignment','top', ...
      'FontSize', 9);
gain_min = min(dcgain_vec); gain_max = max(dcgain_vec);
ratio = abs(gain_min/gain_max);
text(0.21, gain_max*0.6, ...
     sprintf('%.1fx variation\nfrom %.0f to %.0f V/unit', ...
             ratio, gain_max, gain_min), ...
     'FontSize', 9, 'Color', COL_K, 'FontWeight','bold', ...
     'BackgroundColor','w', 'EdgeColor', [0.7 0.7 0.7], 'Margin', 3);
xlabel('Operating point D_0', 'FontSize', 11);
ylabel('DC gain G_{vd}(0) (V/unit)', 'FontSize', 11);
title('(d) Control-to-output DC gain', 'FontSize', 12, 'FontWeight','bold');
xlim([D0_sweep(1)-0.01 D0_sweep(end)+0.01]);
ylim([ymin_dc 0]);
set(gca, 'FontSize', 10);
sgtitle({'Figure 3.10 - Plant variation across the MPPT operating range', ...
         sprintf('Shaded band: D_0 \\geq %.3f where Mode 2 becomes two real poles', D0_regime)}, ...
        'FontSize', 13, 'FontWeight','bold');
drawnow;
print(gcf, 'Fig_3_10_D0_sweep.png', '-dpng', '-r200');
fprintf('\n  Figure saved: Fig_3_10_D0_sweep.png (200 dpi)\n');
%% ========================================================================
%% 13. EXTENSION B: Bode plot of Gvd(s) at the nominal operating point
%% ========================================================================
% Standard frequency-response analysis of the small-signal plant.
% Resonance frequencies are taken from the POLE locations (via damp())
% rather than findpeaks() on the magnitude curve, because the close
% pole-zero cancellation discussed in S3.7.2 can shift the apparent peak.
% ========================================================================
fprintf('\n===== EXTENSION B: Frequency response at D0 = 0.20 =====\n');
w_vec = 2*pi*logspace(0, 5, 5000);
[mag, phase, wout] = bode(sys_ss, w_vec);
mag_dB = 20*log10(squeeze(mag));
phase_deg = squeeze(phase);
f_out = wout / (2*pi);
[wn_all, ~] = damp(sys_ss);
fn_all = wn_all / (2*pi);
fn_unique = unique(round(fn_all, 1));
fn_unique = sort(fn_unique);
f_peak_1 = fn_unique(1);
f_peak_2 = fn_unique(min(2, length(fn_unique)));
DC_gain_value = dcgain(sys_ss);
DC_gain_dB = 20*log10(abs(DC_gain_value));
figure('Color','w','Position',[120 120 1000 700]);
% Magnitude panel
ax1 = subplot(2,1,1);
semilogx(f_out, mag_dB, 'Color', COL_BLUE, 'LineWidth', 2);
hold on; grid on; box on;
yline(DC_gain_dB, '--', 'Color', [0.4 0.4 0.4], 'LineWidth', 1, ...
      'Label', sprintf('DC asymptote (%.1f dB)', DC_gain_dB), ...
      'LabelHorizontalAlignment','left', 'FontSize', 9, ...
      'LabelVerticalAlignment','bottom');
% Mode 1 marker - label below the trace to avoid colliding with title
xline(f_peak_1, ':', 'Color', COL_BLUE, 'LineWidth', 1.2);
text(f_peak_1*0.45, 50, ...
     sprintf('Mode 1\n%.0f Hz', f_peak_1), ...
     'FontSize', 10, 'Color', COL_BLUE, 'FontWeight','bold', ...
     'HorizontalAlignment','center', 'BackgroundColor','w', ...
     'EdgeColor', [0.7 0.7 0.7], 'Margin', 3);
% Mode 2 marker - label to the right of the line
xline(f_peak_2, ':', 'Color', COL_M2, 'LineWidth', 1.2);
text(f_peak_2*2.0, 50, ...
     sprintf('Mode 2\n%.0f Hz', f_peak_2), ...
     'FontSize', 10, 'Color', COL_M2, 'FontWeight','bold', ...
     'HorizontalAlignment','center', 'BackgroundColor','w', ...
     'EdgeColor', [0.7 0.7 0.7], 'Margin', 3);
% Crossover bandwidth recommendation
xline(200, '-.', 'Color', COL_GREEN, 'LineWidth', 1.2, ...
      'Label', 'Suggested controller bandwidth (200 Hz)', ...
      'LabelHorizontalAlignment','right', ...
      'LabelVerticalAlignment','bottom', 'FontSize', 9);
ylabel('Magnitude (dB)', 'FontSize', 12);
title(sprintf('Figure 3.9 - Frequency response of G_{vd}(s) at D_0 = %.2f', D0), ...
      'FontSize', 13, 'FontWeight','bold');
xlim([1 1e5]);
set(gca, 'FontSize', 10);
% Phase panel
ax2 = subplot(2,1,2);
semilogx(f_out, phase_deg, 'Color', COL_BLUE, 'LineWidth', 2);
hold on; grid on; box on;
xline(f_peak_1, ':', 'Color', COL_BLUE, 'LineWidth', 1.2);
xline(f_peak_2, ':', 'Color', COL_M2, 'LineWidth', 1.2);
xline(200, '-.', 'Color', COL_GREEN, 'LineWidth', 1.2);
xlabel('Frequency (Hz)', 'FontSize', 12);
ylabel('Phase (deg)', 'FontSize', 12);
xlim([1 1e5]);
set(gca, 'FontSize', 10);
linkaxes([ax1 ax2], 'x');
drawnow;
print(gcf, 'Fig_3_9_bode.png', '-dpng', '-r200');
fprintf('   Figure saved: Fig_3_9_bode.png (200 dpi)\n');
fprintf('   First resonance peak  ~ %.0f Hz  (Mode 1)\n', f_peak_1);
fprintf('   Second resonance peak ~ %.0f Hz  (Mode 2)\n', f_peak_2);
fprintf('\n   Control-design summary at D_0 = 0.20:\n');
fprintf('      DC gain G_vd(0)              = %+8.2f V/unit (%.1f dB rel. to 1 V)\n', ...
        DC_gain_value, DC_gain_dB);
fprintf('      Mode 1 resonance             = %.0f Hz\n', f_peak_1);
fprintf('      Mode 2 resonance             = %.0f Hz\n', f_peak_2);
fprintf('      Recommended upper bound on closed-loop bandwidth = 200 Hz (1/3 of Mode 1)\n');
%% ========================================================================
%% 14. EXTENSION C: L and C component-sensitivity sweep
%% ========================================================================
% Sweeps the inductance L and capacitance C independently around their
% nominal values, holding the other component and all parasitics fixed.
% At each point, rebuilds the small-signal model and extracts four metrics:
%   - 2% settling time
%   - peak overshoot
%   - dominant-mode natural frequency (f_n)
%   - dominant-mode damping ratio (zeta)
%
% Purpose: addresses the examiner's robustness concern by demonstrating
% that the nominal design (L = 2 mH, C = 20 uF) is robust to the typical
% +/- 20% tolerance band of real components. This is a SENSITIVITY
% analysis (does the design tolerate component variation) and is
% distinct from a DESIGN analysis (what L and C should be chosen).
%
% Output: Fig_3_11_LC_sensitivity.png
% ========================================================================
fprintf('\n===== EXTENSION C: L and C sensitivity sweep =====\n');
% Sweep ranges chosen to span typical component-tolerance bands.
% v8: ranges adjusted to centre on the new nominal (L = 2 mH, C = 20 uF)
% so the +/- 20 % tolerance band appears in the middle of the figure.
L_sweep_vals = (0.5 : 0.25 : 4.0) * 1e-3;      % 0.5 mH to 4.0 mH
C_sweep_vals = (5.0 : 2.5 : 40.0) * 1e-6;      % 5.0 uF to 40.0 uF
NL = length(L_sweep_vals);
NC = length(C_sweep_vals);
% Pre-allocate results (rows = sweep index, columns = [L sweep, C sweep])
ts_L     = zeros(NL, 1);   ts_C     = zeros(NC, 1);
os_L     = zeros(NL, 1);   os_C     = zeros(NC, 1);
fn_L     = zeros(NL, 1);   fn_C     = zeros(NC, 1);
zeta_L   = zeros(NL, 1);   zeta_C   = zeros(NC, 1);
% --- L sweep (C held at nominal = 20 uF) ---
fprintf('\n  Sweeping L (C held at %.1f uF):\n', C1*1e6);
fprintf('    L (mH) | t_s,2%% (ms) | overshoot (%%) | f_n (Hz) | zeta\n');
fprintf('    -------+-------------+---------------+----------+------\n');
for k = 1:NL
    L_k = L_sweep_vals(k);
    % Rebuild A and B with new L (operating point and other parameters unchanged)
    % A matrix includes capacitor ESR (same form as Section 3)
    A_L = [ ( -R*r_C*(D0-1)^2 - (R+r_C)*(D0^2*r_C + r_L_eff) ) / (L_k*(R+r_C)), ...
              -D0*r_C*(D0-1)*(2*R + r_C) / (L_k*(R+r_C)), ...
              D0/L_k, ...
              R*(D0-1) / (L_k*(R+r_C)); ...
            -D0*r_C*(D0-1)*(2*R + r_C) / (L_k*(R+r_C)), ...
             ( -D0^2*R*r_C - (R+r_C)*(r_C*(D0-1)^2 + r_L_eff) ) / (L_k*(R+r_C)), ...
             (D0-1)/L_k, ...
             D0*R / (L_k*(R+r_C)); ...
            -D0/C1,  (1-D0)/C1,  0,  0; ...
             R*(1-D0)/(C2*(R+r_C)), ...
             -D0*R/(C2*(R+r_C)), ...
             0, ...
             -1/(C2*(R+r_C)) ];
    B_L = [ K_d_ind/L_k; K_d_ind/L_k; -K_d_cap/C1; -K_d_cap/C2 ];
    Cm_L = [ R*r_C*(1-D0)/(R+r_C), -R*r_C*D0/(R+r_C), 0, R/(R+r_C) ];
    sys_L = ss(A_L, B_L, Cm_L, Dm);
    % Step-response metrics
    t_test = 0:1e-5:0.05;
    [y_test, ~] = step(sys_L, t_test);
    info_test = stepinfo(y_test, t_test, y_test(end), 'SettlingTimeThreshold', 0.02);
    ts_L(k) = info_test.SettlingTime;
    os_L(k) = info_test.Overshoot;
    % Dominant-mode f_n and zeta (lowest-frequency complex pair)
    P_L = pole(sys_L);
    P_cplx = P_L(abs(imag(P_L)) > 1e-6);
    if ~isempty(P_cplx)
        wn_cplx = unique(abs(P_cplx));
        wn_cplx = sort(wn_cplx);
        fn_L(k) = wn_cplx(1) / (2*pi);
        idx1 = find(abs(abs(P_cplx) - wn_cplx(1)) < 1e-3, 1);
        zeta_L(k) = -real(P_cplx(idx1)) / abs(P_cplx(idx1));
    else
        fn_L(k) = NaN; zeta_L(k) = NaN;
    end
    fprintf('    %5.2f  | %10.2f  | %12.2f  | %7.1f  | %.3f\n', ...
            L_k*1e3, ts_L(k)*1e3, os_L(k), fn_L(k), zeta_L(k));
end
% --- C sweep (L held at nominal = 2 mH) ---
fprintf('\n  Sweeping C (L held at %.1f mH):\n', L1*1e3);
fprintf('    C (uF) | t_s,2%% (ms) | overshoot (%%) | f_n (Hz) | zeta\n');
fprintf('    -------+-------------+---------------+----------+------\n');
for k = 1:NC
    C_k = C_sweep_vals(k);
    % A matrix with capacitor ESR
    A_C = [ ( -R*r_C*(D0-1)^2 - (R+r_C)*(D0^2*r_C + r_L_eff) ) / (L1*(R+r_C)), ...
              -D0*r_C*(D0-1)*(2*R + r_C) / (L1*(R+r_C)), ...
              D0/L1, ...
              R*(D0-1) / (L1*(R+r_C)); ...
            -D0*r_C*(D0-1)*(2*R + r_C) / (L2*(R+r_C)), ...
             ( -D0^2*R*r_C - (R+r_C)*(r_C*(D0-1)^2 + r_L_eff) ) / (L2*(R+r_C)), ...
             (D0-1)/L2, ...
             D0*R / (L2*(R+r_C)); ...
            -D0/C_k,  (1-D0)/C_k,  0,  0; ...
             R*(1-D0)/(C_k*(R+r_C)), ...
             -D0*R/(C_k*(R+r_C)), ...
             0, ...
             -1/(C_k*(R+r_C)) ];
    B_C = [ K_d_ind/L1; K_d_ind/L2; -K_d_cap/C_k; -K_d_cap/C_k ];
    Cm_C = [ R*r_C*(1-D0)/(R+r_C), -R*r_C*D0/(R+r_C), 0, R/(R+r_C) ];
    sys_C = ss(A_C, B_C, Cm_C, Dm);
    t_test = 0:1e-5:0.05;
    [y_test, ~] = step(sys_C, t_test);
    info_test = stepinfo(y_test, t_test, y_test(end), 'SettlingTimeThreshold', 0.02);
    ts_C(k) = info_test.SettlingTime;
    os_C(k) = info_test.Overshoot;
    P_C = pole(sys_C);
    P_cplx = P_C(abs(imag(P_C)) > 1e-6);
    if ~isempty(P_cplx)
        wn_cplx = unique(abs(P_cplx));
        wn_cplx = sort(wn_cplx);
        fn_C(k) = wn_cplx(1) / (2*pi);
        idx1 = find(abs(abs(P_cplx) - wn_cplx(1)) < 1e-3, 1);
        zeta_C(k) = -real(P_cplx(idx1)) / abs(P_cplx(idx1));
    else
        fn_C(k) = NaN; zeta_C(k) = NaN;
    end
    fprintf('    %5.1f  | %10.2f  | %12.2f  | %7.1f  | %.3f\n', ...
            C_k*1e6, ts_C(k)*1e3, os_C(k), fn_C(k), zeta_C(k));
end
% --- Plot: 4 panels x 2 columns (L sweep on left, C sweep on right) ----
figure('Color','w','Position',[80 80 1200 800]);
% Tolerance band for shading: +/- 20% around nominal
L_tol_lo = L1 * 0.8 * 1e3;  L_tol_hi = L1 * 1.2 * 1e3;  % in mH
C_tol_lo = C1 * 0.8 * 1e6;  C_tol_hi = C1 * 1.2 * 1e6;  % in uF
COL_TOL = [0.83 0.95 0.83];   % light green for tolerance band
% --- Row 1: Settling time ---
subplot(4,2,1); hold on; grid on; box on;
ymax = max(ts_L)*1.15*1e3;
patch([L_tol_lo L_tol_hi L_tol_hi L_tol_lo], [0 0 ymax ymax], COL_TOL, ...
      'EdgeColor','none', 'FaceAlpha', 0.4, 'HandleVisibility','off');
xline(L1*1e3, '--', 'Color', [0.4 0.4 0.4], 'LineWidth', 1.2, ...
      'Label', 'nominal', 'LabelOrientation','horizontal', ...
      'LabelHorizontalAlignment','center', 'FontSize', 9, 'HandleVisibility','off');
plot(L_sweep_vals*1e3, ts_L*1e3, '-o', 'Color', COL_BLUE, ...
     'MarkerFaceColor', COL_BLUE, 'LineWidth', 1.6, 'MarkerSize', 5);
yline(5, ':', 'Color', COL_GREEN, 'LineWidth', 1, ...
      'Label', '5 ms target', 'LabelHorizontalAlignment','left', 'FontSize', 8);
xlabel('L (mH)', 'FontSize', 10);
ylabel('t_{s,2%} (ms)', 'FontSize', 10);
title('(a) Settling time vs L (C = nominal)', 'FontSize', 11, 'FontWeight','bold');
set(gca, 'FontSize', 9);
ylim([0 ymax]);
subplot(4,2,2); hold on; grid on; box on;
ymax = max(ts_C)*1.15*1e3;
patch([C_tol_lo C_tol_hi C_tol_hi C_tol_lo], [0 0 ymax ymax], COL_TOL, ...
      'EdgeColor','none', 'FaceAlpha', 0.4, 'HandleVisibility','off');
xline(C1*1e6, '--', 'Color', [0.4 0.4 0.4], 'LineWidth', 1.2, ...
      'Label', 'nominal', 'LabelOrientation','horizontal', ...
      'LabelHorizontalAlignment','center', 'FontSize', 9, 'HandleVisibility','off');
plot(C_sweep_vals*1e6, ts_C*1e3, '-s', 'Color', COL_M2, ...
     'MarkerFaceColor', COL_M2, 'LineWidth', 1.6, 'MarkerSize', 5);
yline(5, ':', 'Color', COL_GREEN, 'LineWidth', 1, ...
      'Label', '5 ms target', 'LabelHorizontalAlignment','left', 'FontSize', 8);
xlabel('C (\muF)', 'FontSize', 10);
ylabel('t_{s,2%} (ms)', 'FontSize', 10);
title('(b) Settling time vs C (L = nominal)', 'FontSize', 11, 'FontWeight','bold');
set(gca, 'FontSize', 9);
ylim([0 ymax]);
% --- Row 2: Overshoot ---
subplot(4,2,3); hold on; grid on; box on;
ymax = max([max(os_L)*1.15 1]);
patch([L_tol_lo L_tol_hi L_tol_hi L_tol_lo], [0 0 ymax ymax], COL_TOL, ...
      'EdgeColor','none', 'FaceAlpha', 0.4, 'HandleVisibility','off');
xline(L1*1e3, '--', 'Color', [0.4 0.4 0.4], 'LineWidth', 1.2, ...
      'Label', 'nominal', 'LabelOrientation','horizontal', ...
      'LabelHorizontalAlignment','center', 'FontSize', 9, 'HandleVisibility','off');
plot(L_sweep_vals*1e3, os_L, '-o', 'Color', COL_BLUE, ...
     'MarkerFaceColor', COL_BLUE, 'LineWidth', 1.6, 'MarkerSize', 5);
xlabel('L (mH)', 'FontSize', 10);
ylabel('Overshoot (%)', 'FontSize', 10);
title('(c) Overshoot vs L', 'FontSize', 11, 'FontWeight','bold');
set(gca, 'FontSize', 9);
ylim([0 ymax]);
subplot(4,2,4); hold on; grid on; box on;
ymax = max([max(os_C)*1.15 1]);
patch([C_tol_lo C_tol_hi C_tol_hi C_tol_lo], [0 0 ymax ymax], COL_TOL, ...
      'EdgeColor','none', 'FaceAlpha', 0.4, 'HandleVisibility','off');
xline(C1*1e6, '--', 'Color', [0.4 0.4 0.4], 'LineWidth', 1.2, ...
      'Label', 'nominal', 'LabelOrientation','horizontal', ...
      'LabelHorizontalAlignment','center', 'FontSize', 9, 'HandleVisibility','off');
plot(C_sweep_vals*1e6, os_C, '-s', 'Color', COL_M2, ...
     'MarkerFaceColor', COL_M2, 'LineWidth', 1.6, 'MarkerSize', 5);
xlabel('C (\muF)', 'FontSize', 10);
ylabel('Overshoot (%)', 'FontSize', 10);
title('(d) Overshoot vs C', 'FontSize', 11, 'FontWeight','bold');
set(gca, 'FontSize', 9);
ylim([0 ymax]);
% --- Row 3: Natural frequency ---
subplot(4,2,5); hold on; grid on; box on;
ymin = min(fn_L)*0.9;  ymax = max(fn_L)*1.1;
patch([L_tol_lo L_tol_hi L_tol_hi L_tol_lo], [ymin ymin ymax ymax], COL_TOL, ...
      'EdgeColor','none', 'FaceAlpha', 0.4, 'HandleVisibility','off');
xline(L1*1e3, '--', 'Color', [0.4 0.4 0.4], 'LineWidth', 1.2, ...
      'Label', 'nominal', 'LabelOrientation','horizontal', ...
      'LabelHorizontalAlignment','center', 'FontSize', 9, 'HandleVisibility','off');
plot(L_sweep_vals*1e3, fn_L, '-o', 'Color', COL_BLUE, ...
     'MarkerFaceColor', COL_BLUE, 'LineWidth', 1.6, 'MarkerSize', 5);
xlabel('L (mH)', 'FontSize', 10);
ylabel('f_n (Hz)', 'FontSize', 10);
title('(e) Natural frequency vs L', 'FontSize', 11, 'FontWeight','bold');
set(gca, 'FontSize', 9);
ylim([ymin ymax]);
subplot(4,2,6); hold on; grid on; box on;
ymin = min(fn_C)*0.9;  ymax = max(fn_C)*1.1;
patch([C_tol_lo C_tol_hi C_tol_hi C_tol_lo], [ymin ymin ymax ymax], COL_TOL, ...
      'EdgeColor','none', 'FaceAlpha', 0.4, 'HandleVisibility','off');
xline(C1*1e6, '--', 'Color', [0.4 0.4 0.4], 'LineWidth', 1.2, ...
      'Label', 'nominal', 'LabelOrientation','horizontal', ...
      'LabelHorizontalAlignment','center', 'FontSize', 9, 'HandleVisibility','off');
plot(C_sweep_vals*1e6, fn_C, '-s', 'Color', COL_M2, ...
     'MarkerFaceColor', COL_M2, 'LineWidth', 1.6, 'MarkerSize', 5);
xlabel('C (\muF)', 'FontSize', 10);
ylabel('f_n (Hz)', 'FontSize', 10);
title('(f) Natural frequency vs C', 'FontSize', 11, 'FontWeight','bold');
set(gca, 'FontSize', 9);
ylim([ymin ymax]);
% --- Row 4: Damping ratio ---
subplot(4,2,7); hold on; grid on; box on;
ymax = max([max(zeta_L)*1.15 0.8]);
patch([L_tol_lo L_tol_hi L_tol_hi L_tol_lo], [0 0 ymax ymax], COL_TOL, ...
      'EdgeColor','none', 'FaceAlpha', 0.4, 'HandleVisibility','off');
xline(L1*1e3, '--', 'Color', [0.4 0.4 0.4], 'LineWidth', 1.2, ...
      'Label', 'nominal', 'LabelOrientation','horizontal', ...
      'LabelHorizontalAlignment','center', 'FontSize', 9, 'HandleVisibility','off');
plot(L_sweep_vals*1e3, zeta_L, '-o', 'Color', COL_BLUE, ...
     'MarkerFaceColor', COL_BLUE, 'LineWidth', 1.6, 'MarkerSize', 5);
yline(0.7, ':', 'Color', COL_GREEN, 'LineWidth', 1, ...
      'Label', '\zeta = 0.7', 'LabelHorizontalAlignment','left', 'FontSize', 8);
xlabel('L (mH)', 'FontSize', 10);
ylabel('Damping ratio \zeta', 'FontSize', 10);
title('(g) Damping ratio vs L', 'FontSize', 11, 'FontWeight','bold');
set(gca, 'FontSize', 9);
ylim([0 ymax]);
subplot(4,2,8); hold on; grid on; box on;
ymax = max([max(zeta_C)*1.15 0.8]);
patch([C_tol_lo C_tol_hi C_tol_hi C_tol_lo], [0 0 ymax ymax], COL_TOL, ...
      'EdgeColor','none', 'FaceAlpha', 0.4, 'HandleVisibility','off');
xline(C1*1e6, '--', 'Color', [0.4 0.4 0.4], 'LineWidth', 1.2, ...
      'Label', 'nominal', 'LabelOrientation','horizontal', ...
      'LabelHorizontalAlignment','center', 'FontSize', 9, 'HandleVisibility','off');
plot(C_sweep_vals*1e6, zeta_C, '-s', 'Color', COL_M2, ...
     'MarkerFaceColor', COL_M2, 'LineWidth', 1.6, 'MarkerSize', 5);
yline(0.7, ':', 'Color', COL_GREEN, 'LineWidth', 1, ...
      'Label', '\zeta = 0.7', 'LabelHorizontalAlignment','left', 'FontSize', 8);
xlabel('C (\muF)', 'FontSize', 10);
ylabel('Damping ratio \zeta', 'FontSize', 10);
title('(h) Damping ratio vs C', 'FontSize', 11, 'FontWeight','bold');
set(gca, 'FontSize', 9);
ylim([0 ymax]);
sgtitle({'Figure 3.11 - Sensitivity of converter dynamics to L and C variation', ...
         'Green band: \pm 20% tolerance around nominal (L = 2 mH, C = 20 \muF)'}, ...
        'FontSize', 13, 'FontWeight','bold');
drawnow;
print(gcf, 'Fig_3_11_LC_sensitivity.png', '-dpng', '-r200');
fprintf('\n  Figure saved: Fig_3_11_LC_sensitivity.png (200 dpi)\n');
% Print summary of tolerance-band behaviour
fprintf('\n  Within +/- 20%% tolerance band:\n');
L_in_tol = (L_sweep_vals >= L1*0.8) & (L_sweep_vals <= L1*1.2);
C_in_tol = (C_sweep_vals >= C1*0.8) & (C_sweep_vals <= C1*1.2);
fprintf('    L sweep: t_s ranges from %.2f to %.2f ms\n', ...
        min(ts_L(L_in_tol))*1e3, max(ts_L(L_in_tol))*1e3);
fprintf('    C sweep: t_s ranges from %.2f to %.2f ms\n', ...
        min(ts_C(C_in_tol))*1e3, max(ts_C(C_in_tol))*1e3);
fprintf('    L sweep: zeta ranges from %.3f to %.3f\n', ...
        min(zeta_L(L_in_tol)), max(zeta_L(L_in_tol)));
fprintf('    C sweep: zeta ranges from %.3f to %.3f\n', ...
        min(zeta_C(C_in_tol)), max(zeta_C(C_in_tol)));
%% ========================================================================
%% 15. EXTENSION D: Linearisation error vs perturbation magnitude
%% ========================================================================
% Computes the linearisation error epsilon(d_hat) across the full range
% 0 < d_hat < 0.15, and identifies the 2% and 5% validity boundaries
% numerically.
%
% The linearisation error is defined as:
%   epsilon(d_hat) = ( V_C2_ss_linear - V_C2_ss_nonlinear ) / V_C2_ss_nonlinear
%
% where:
%   V_C2_ss_linear    = V_C2,0 + dcgain(sys_ss) * d_hat      (linear prediction)
%   V_C2_ss_nonlinear = ((1-2*(D0+d_hat))/(1-(D0+d_hat))) * V_g  (exact average)
%
% This is the analysis referenced by section 3.5.5 of the thesis chapter:
% the smooth growth of error across the validity boundary, with the three
% step-response studies (d_hat = 0.01, 0.05, 0.10) marked as data points
% on the curve.
%
% Output: Fig_3_7b_linearisation_error.png
%   (companion to the Simscape-generated Fig 3.7 which lives in
%   topology_Cslx.slx)
% ========================================================================
fprintf('\n===== EXTENSION D: Linearisation error sweep =====\n');
% Sweep range. Lower bound > 0 to avoid div-by-zero in the percent error.
d_hat_sweep = 0.001 : 0.001 : 0.150;
N_d = length(d_hat_sweep);
eps_pct = zeros(N_d, 1);    % linearisation error in percent
% DC gain of the linearised plant (computed once, used for all d_hat values)
G0 = dcgain(sys_ss);        % V/unit, expected to be approximately -832 V
for k = 1:N_d
    d_h = d_hat_sweep(k);
    % Linear prediction: small-signal Final-Value Theorem
    V_C2_linear = V_c2 + G0 * d_h;
    % Exact (averaged-model) nonlinear steady state at perturbed duty
    [Vo_k, ~, ~, ~, ~, ~] = operating_point(V_g, D0 + d_h, P_rated);
    eps_pct(k) = 100 * (V_C2_linear - Vo_k) / Vo_k;
end
% Locate the validity boundaries (where |error| crosses 2% and 5%)
abs_err = abs(eps_pct);
idx_2pct = find(abs_err >= 2.0, 1, 'first');
idx_5pct = find(abs_err >= 5.0, 1, 'first');
if ~isempty(idx_2pct)
    d_2pct = d_hat_sweep(idx_2pct);
    fprintf('   2%% validity boundary at d_hat = %.4f (%.1f%% of D0)\n', ...
            d_2pct, 100*d_2pct/D0);
else
    d_2pct = NaN;
end
if ~isempty(idx_5pct)
    d_5pct = d_hat_sweep(idx_5pct);
    fprintf('   5%% validity boundary at d_hat = %.4f (%.1f%% of D0)\n', ...
            d_5pct, 100*d_5pct/D0);
else
    d_5pct = NaN;
end
% Reference values for the three step studies (calculated for plot markers)
d_hat_markers = [d_hat_1, d_hat_2, 0.10];
eps_markers   = zeros(1, 3);
for k = 1:3
    [Vo_m, ~, ~, ~, ~, ~] = operating_point(V_g, D0 + d_hat_markers(k), P_rated);
    eps_markers(k) = 100 * ((V_c2 + G0 * d_hat_markers(k)) - Vo_m) / Vo_m;
end
% --- Polished plot --------------------------------------------------
figure('Color','w','Position',[160 160 1000 600]);
hold on; grid on; box on;
% Shade the 2% validity region in green
if ~isnan(d_2pct)
    patch([0 d_2pct d_2pct 0], [-15 -15 15 15], ...
          [0.83 0.95 0.83], 'EdgeColor','none', 'FaceAlpha', 0.5, ...
          'HandleVisibility','off');
end
% Shade the 2%-5% region in yellow (caution zone)
if ~isnan(d_2pct) && ~isnan(d_5pct)
    patch([d_2pct d_5pct d_5pct d_2pct], [-15 -15 15 15], ...
          [1.0 0.95 0.7], 'EdgeColor','none', 'FaceAlpha', 0.5, ...
          'HandleVisibility','off');
end
% Plot the linearisation-error curve
h_curve = plot(d_hat_sweep, eps_pct, '-', 'Color', COL_RED, ...
               'LineWidth', 2, 'DisplayName', 'Linearisation error \epsilon');
% Tolerance lines: +/- 2% and +/- 5%
yline( 2, ':', 'Color', [0.0 0.5 0.2], 'LineWidth', 1.2);
yline(-2, ':', 'Color', [0.0 0.5 0.2], 'LineWidth', 1.2);
yline( 5, ':', 'Color', [0.7 0.5 0.0], 'LineWidth', 1.2);
yline(-5, ':', 'Color', [0.7 0.5 0.0], 'LineWidth', 1.2);
% Vertical lines at the boundaries
if ~isnan(d_2pct)
    xline(d_2pct, '--', 'Color', [0.0 0.5 0.2], 'LineWidth', 1.5);
end
if ~isnan(d_5pct)
    xline(d_5pct, '--', 'Color', [0.7 0.5 0.0], 'LineWidth', 1.5);
end
% Mark the three step studies as data points on the curve
h_studies = plot(d_hat_markers, eps_markers, 'o', 'MarkerSize', 10, ...
                 'MarkerFaceColor', COL_BLUE, 'MarkerEdgeColor', 'k', ...
                 'LineWidth', 1.2, 'DisplayName', 'Step studies (1,2,3)');
% Label each study marker
study_labels = {'Study 1', 'Study 2', 'Study 3'};
for k = 1:3
    text(d_hat_markers(k), eps_markers(k) - 0.7, ...
         sprintf('%s\n\\Deltad=%.3f\n\\epsilon=%.2f%%', ...
                 study_labels{k}, d_hat_markers(k), eps_markers(k)), ...
         'HorizontalAlignment','center', 'VerticalAlignment','top', ...
         'FontSize', 9, 'FontWeight','bold', 'Color', COL_BLUE, ...
         'BackgroundColor', 'w', 'EdgeColor', [0.7 0.7 0.7], 'Margin', 3);
end
% Boundary text labels (outside the curve area, in the margins)
if ~isnan(d_2pct)
    text(d_2pct, 13, sprintf(' 2%% boundary\n d_{\\^} = %.3f', d_2pct), ...
         'HorizontalAlignment','left', 'VerticalAlignment','top', ...
         'FontSize', 9, 'Color', [0.0 0.5 0.2], 'FontWeight','bold');
end
if ~isnan(d_5pct)
    text(d_5pct, 13, sprintf(' 5%% boundary\n d_{\\^} = %.3f', d_5pct), ...
         'HorizontalAlignment','left', 'VerticalAlignment','top', ...
         'FontSize', 9, 'Color', [0.7 0.5 0.0], 'FontWeight','bold');
end
% Region labels at the top of the plot
text(d_2pct/2, -12, 'Valid', ...
     'HorizontalAlignment','center', 'FontSize', 10, ...
     'FontWeight','bold', 'Color', [0.0 0.4 0.15], 'FontAngle','italic');
if ~isnan(d_2pct) && ~isnan(d_5pct)
    text((d_2pct + d_5pct)/2, -12, 'Caution', ...
         'HorizontalAlignment','center', 'FontSize', 10, ...
         'FontWeight','bold', 'Color', [0.6 0.4 0.0], 'FontAngle','italic');
end
if ~isnan(d_5pct)
    text((d_5pct + 0.15)/2, -12, 'Invalid', ...
         'HorizontalAlignment','center', 'FontSize', 10, ...
         'FontWeight','bold', 'Color', [0.6 0.0 0.0], 'FontAngle','italic');
end
xlabel('Duty-ratio perturbation \Deltad', 'FontSize', 12);
ylabel('Linearisation error \epsilon (%)', 'FontSize', 12);
title({'Figure 3.7b - Linearisation error \epsilon vs perturbation magnitude', ...
       sprintf('Linearised about D_0 = %.2f', D0)}, ...
      'FontSize', 13, 'FontWeight','bold');
legend([h_curve h_studies], 'Location', 'southwest', 'FontSize', 10, ...
       'Box', 'on', 'EdgeColor', [0.7 0.7 0.7]);
set(gca, 'FontSize', 10);
xlim([0 0.15]);
ylim([-15 15]);
drawnow;
print(gcf, 'Fig_3_7b_linearisation_error.png', '-dpng', '-r200');
fprintf('\n  Figure saved: Fig_3_7b_linearisation_error.png (200 dpi)\n');
% Print numerical summary
fprintf('\n  Linearisation error at the three step-study perturbations:\n');
fprintf('    Study 1: d_hat = %.3f -> epsilon = %+.3f %%\n', d_hat_markers(1), eps_markers(1));
fprintf('    Study 2: d_hat = %.3f -> epsilon = %+.3f %%\n', d_hat_markers(2), eps_markers(2));
fprintf('    Study 3: d_hat = %.3f -> epsilon = %+.3f %%\n', d_hat_markers(3), eps_markers(3));
fprintf('\n--- SS_Script_v8.m complete ---\n\n');
%% ========================================================================
%% LOCAL FUNCTIONS
%% ========================================================================
% Note on naming: the function arguments are named 'D' (generic) rather
% than 'D0' because these helpers accept ANY duty ratio - the main script
% calls them with D0 (the operating point), D0 + d_hat (for nonlinear
% targets), and D_new (for Study 3). Using 'D' as the argument name
% reflects that it is a generic duty-ratio input, not the specific
% linearisation point.
% ------------------------------------------------------------------------
function [Vo, V_c1, V_c2, I_L1, I_L2, R] = operating_point(V_g, D, P_rated)
%OPERATING_POINT  Steady-state values of the semi-Z-source DC-DC converter.
%   Returns the output voltage, both capacitor voltages, both inductor
%   currents, and the equivalent load resistance for the averaged model,
%   evaluated at ANY duty ratio D (not just the linearisation point D0).
    Vo   = ((1 - 2*D)/(1 - D)) * V_g;
    V_c2 = Vo;
    V_c1 = ((1 - D)/D) * (V_g - Vo);
    R    = Vo^2 / P_rated;
    I_L2 = (Vo/R) * (D/(1 - D));
    I_L1 = ((1 - D)/D) * I_L2;
end
function [y, info, V_true] = run_step_study(sys_ss, V_c2_0, V_g, D0, ...
                                             d_hat, t, t_step, P_rated)
%RUN_STEP_STUDY  Run one step on the small-signal model and return the
%   deviation y, stepinfo struct, and nonlinear-steady-state target.
    u = d_hat * (t >= t_step);
    [y, ~] = lsim(sys_ss, u, t);
    info = stepinfo(y, t - t_step, y(end), ...
                    'SettlingTimeThreshold', 0.02);
    [Vo_new, ~, ~, ~, ~, ~] = operating_point(V_g, D0 + d_hat, P_rated);
    V_true = Vo_new;
    fprintf('   d_hat = %.3f\n', d_hat);
    fprintf('      Rise time         = %.3f ms\n', 1e3*info.RiseTime);
    fprintf('      Settling (2%%)    = %.3f ms\n', 1e3*info.SettlingTime);
    fprintf('      Overshoot         = %.2f %%\n', info.Overshoot);
    fprintf('      ss() final v_C2   = %.3f V\n', V_c2_0 + y(end));
    fprintf('      Nonlinear target  = %.3f V\n', V_true);
end
